### ISSUE TITLE
This addon is no longer working

### ISSUE THREAD

**Issue by muhammadGagah** [alekssamos/crypto_info#1]
Hi, can you update this addon again? Because I found, this addon is not working anymore.

**Comment by alekssamos** [comment]
Hello. Thanks for letting me know. 
Yes, the site now gives information not to HTML pages, but loads it via javascript. 
I'll update it soon. Wait.

**Comment by alekssamos** [comment]
Try the new version [2022.05.14](https://github.com/alekssamos/crypto_info/releases/tag/v2022.05.14)
